FROM move4d_ros:vol

COPY ./move4d/catkin_ws  /move4d/catkin_ws
COPY ./move4d/lib  /move4d/lib
COPY ./move4d/run.bash /move4d/
COPY ./move4d/data/move4d /move4d/data/move4d

CMD ["bash", "/move4d/run.bash"]
